djangoProject3/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import homepage, header, footer,about_us,news_page

from djangoProject3 import settings

urlpatterns = [
    path('', homepage),
    path('', include('shop_account.urls')),
    path('', include('shop_products.urls')),
    path('', include('shop_contactus.urls')),
    path('', include('shop_order.urls')),
    path('header', header, name="header"),
    path('footer', footer, name="footer"),
    path('about-us',about_us),
    path('news',news_page),
    path('admin/', admin.site.urls),


]

if settings.DEBUG:
    # add root static files
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # add media static files
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop_order/urls.py
from django.urls import path
from .views import add_user_order,user_open_order,remove_order_detail
urlpatterns = [

path('user-order',add_user_order),
path('open-order',user_open_order),
path('remove-order-detail/<detail_id>',remove_order_detail),

]

shop_products/urls.py
from django.urls import path
from .views import ProductsList, product_detail, SearchProductsView, ProductsListByCategory,products_category_partial

urlpatterns = [

    path('products', ProductsList.as_view()),
    path('products/<productid>/<title>', product_detail),
    path('products/<category_name>', ProductsListByCategory.as_view()),
    path('products/search', SearchProductsView.as_view()),
    path('products_category_partial', products_category_partial,name="products_category_partial"),

]

shop_products/models.py
from django.db.models import Q
from django.db import models
import os

# Create your models here.
from shop_category.models import ProductCategory


def get_filename_ext(filepath):
    base_name = os.path.basename(filepath)
    name, ext = os.path.splitext(base_name)
    return name, ext


def upload_image_path(instance, filename):
    name, ext = get_filename_ext(filename)
    final_name = f"{instance.id}-{instance.title}{ext}"

    return f"products/{final_name}"


def upload_galleries_image_path(instance, filename):
    name, ext = get_filename_ext(filename)
    final_name = f"{instance.id}-{instance.title}{ext}"

    return f"products/galleries/{final_name}"


class ProductManager(models.Manager):
    def get_active_products(self):
        return self.get_queryset().filter(active=True)

    def get_products_by_category(self, category_name):
        return self.get_queryset().filter(categories__name__iexact=category_name, active=True)

    def get_by_id(self, product_id):
        qs = self.get_queryset().filter(id=product_id)
        if qs.count() == 1:
            return qs.first()
        else:
            return None


def Searh(self, query):
    lookup = (
            Q(title__icontains=query) |
            Q(description__icontains=query) |
            Q(tag__title__icontains=query)
    )

    return self.get_queryset().filter(lookup, active=True).distinct()


class Product(models.Model):
    title = models.CharField(max_length=120, verbose_name="عنوان")
    description = models.TextField(max_length=10000, verbose_name="توضیحات")
    short_desc = models.CharField(max_length=50, verbose_name="توضیح کوتاه")
    price = models.IntegerField(verbose_name="قیمت")
    image = models.ImageField(upload_to=upload_image_path, null=True, blank=True, verbose_name="عکس")
    active = models.BooleanField(default=False, verbose_name="فعال/غیر فعال")
    categories = models.ManyToManyField(ProductCategory, blank=True, verbose_name="دسته بندی ها")
    visit_count = models.IntegerField(default=0, verbose_name="تعداد بازدید")

    objects = ProductManager()

    class Meta:
        verbose_name = "محصول"
        verbose_name_plural = "محصولات"

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return f"/products/{self.id}/{self.title.replace('', '-')}"


class Comment(models.Model):
    post = models.ForeignKey(Product, related_name="comments", on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.post} {self.name}"


class Gallery(models.Model):
    title = models.CharField(max_length=120, verbose_name="عنوان")
    image = models.ImageField(upload_to=upload_galleries_image_path, verbose_name="عکس")
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    class Meta:
        verbose_name = "تصویر"
        verbose_name_plural = "گالری تصویر"

    def __str__(self):
        return self.title

shop_products/forms.py
from django import forms
from django.core import validators


class PostForm(forms.Form):
    full_name = forms.CharField(
        widget=forms.TextInput
        (attrs={"placeholder": "لطفا نام خود را وارد کنید", "class": "form-control"}),
        label="نام و نام خانوادکی",
        validators=[
            validators.MaxLengthValidator(20, message="بیشتر از حد مجاز"),
            validators.MinLengthValidator(5, message="کمتر از حد مجاز")
        ]
    )
    email = forms.EmailField(
        widget=forms.EmailInput
        (attrs={"placeholder": "لطفا ایمیل خود را وارد کنید", "class": "form-control"}),
        label="ایمیل",
        validators=[
            validators.MaxLengthValidator(100, message="بیشتر از حد مجاز")

        ]
    )


    text = forms.CharField(
        widget=forms.Textarea(attrs={"placeholder": " لطفا پیام خود را وارد کنید", "row": 8}),
        label="پیغام",

    )

shop_products/views.py
import itertools

from django.http import Http404
from django.shortcuts import render
from django.views.generic import ListView

from shop_order.forms import UserNewOrderForm
from .forms import PostForm
from .models import Product, Gallery
from shop_tag.models import Tag
from shop_category.models import ProductCategory


# Create your views here.


class ProductsList(ListView):
    template_name = "products/products_list.html"
    paginate_by = 6

    def get_queryset(self):
        return Product.objects.get_active_products()


class ProductsListByCategory(ListView):
    template_name = "products/products_list.html"
    paginate_by = 6

    def get_queryset(self):
        category_name = self.kwargs["category_name"]
        category = ProductCategory.objects.filter(name__iexact=category_name).first()
        if category is None:
            raise Http404("صفحه ی مورد نظر یافت نشد")
        return Product.objects.get_products_by_category(category_name)


def my_grouper(n, iterable):
    args = [iter(iterable)] * n
    return ([e for e in t if e is not None] for t in itertools.zip_longest(*args))


def product_detail(request, *args, **kwargs):
    product_id = kwargs["productid"]

    new_order_form = UserNewOrderForm(request.POST or None,initial={"product_id":product_id})

    product:Product = Product.objects.get_by_id(product_id)
    if product is None or not product.active:
        raise Http404

    product.visit_count +=1
    product.save()

    related_products = Product.objects.get_queryset().filter(categories__product=product).distinct()

    grouped_related_products = my_grouper(3, related_products)

    galleries = Gallery.objects.filter(product_id=product_id)
    grouped_galleries = list(my_grouper(3, galleries))

    # code behind the post form
    post_form = PostForm(request.POST or None)
    if post_form.is_valid():
        full_name = post_form.cleaned_data.get("name")
        email = post_form.cleaned_data.get("email")

        text = post_form.cleaned_data.get("body")
        PostForm.objects.create(full_name=full_name, email=email, text=text, )
        post_form.save()
        # todo : show user a success message
        post_form = PostForm

    context = {
        "product": product,
        "post_form": post_form,
        "galleries": grouped_galleries,
        "related_products": grouped_related_products,
        "new_order_form": new_order_form
    }

    tag = Tag.objects.first()
    print(tag.products.all())

    return render(request, "products/product_detail.html", context)


class SearchProductsView(ListView):
    template_name = "products/products_list.html"
    paginate_by = 6

    def get_queryset(self):
        request = self.request
        query = request.GET.get("q")
        if query is not None:
            return Product.objects.Searh(query)

        return Product.objects.get_active_products()


def products_category_partial(request):
    categories = ProductCategory.objects.all()
    context = {
        "categories": categories
    }
    return render(request, "products/products_categories_partial.html", context)

shop_products/templates/products/product_detail.html
{% extends "shared/_MainLayout.html" %}
{% load static %}
{% load render_partial %}
{% block content %}
    <section>
        <div class="container">
            <div class="row">

                <div class="col-sm-9 padding-right">
                    <div class="product-details"><!--product-details-->
                        <div class="col-sm-5">
                            <div class="view-product">
                                <img src="{{ product.image.url }}" alt="">
                                <h3>بزرگنمایـی</h3>
                            </div>
                            <div id="similar-product" class="carousel slide" data-ride="carousel">

                                <!-- Wrapper for slides -->
                                <div class="carousel-inner">
                                    {% for gallery_list in galleries %}
                                        <div class="item {{ forloop.first|yesno:'active,' }}">
                                            {% for gallery in gallery_list %}
                                                <a href="">
                                                    <img src="{{ gallery.image.url }}"
                                                         alt="" style="width: 85px; height: 85px"></a>

                                            {% endfor %}

                                        </div>
                                    {% endfor %}


                                </div>

                                <!-- Controls -->
                                <a class="right item-control" href="#similar-product" data-slide="next">
                                    <i class="fa fa-angle-right"></i>
                                </a>
                                <a class="left item-control" href="#similar-product" data-slide="prev">
                                    <i class="fa fa-angle-left"></i>
                                </a>
                            </div>

                        </div>
                        <div class="col-sm-7">
                            <div class="product-information"><!--/product-information-->
                                <img src="{% static "images/product-details/new.png" %}" class="newarrival" alt="">
                                <div>
                                    <h2>{{ product.title }}</h2>
                                    <p>شناسـه :{{ product.id }}</p>
                                </div>
                                <div>
									<span>
										<span>قیمت : {{ product.price }}</span>
									</span>
                                    <span>
                                        <form method="post" action="/user-order">
                                            {% csrf_token %}
                                            {{ new_order_form.product_id }}
                                            	<label>تعداد :</label>

                                            {{ new_order_form.count }}
										<button type="submit" class="btn btn-fefault cart">
											<i class="fa fa-shopping-cart"></i>
											افـزودن به سبـد خریـد
										</button>
                                        </form>

									</span>
                                </div>
                                <div>
                                    <p><b>موجـودی :</b> در انبـار موجود می باشد</p>
                                    <p><b>شرایـط :</b> جدیـد</p>
                                    <p><b>برنـد :</b> برنـد </p>
                                </div>


                            </div><!--/product-information-->
                        </div>
                    </div><!--/product-details-->

                    <div class="category-tab shop-details-tab"><!--category-tab-->
                        <div class="col-sm-12">
                            <ul class="nav nav-tabs">
                                <li><a href="#details" data-toggle="tab">جزئیات</a></li>

                                <li><a href="#tag" data-toggle="tab">برچسب</a></li>
                                <li class="active"><a href="#reviews" data-toggle="tab">نظرات</a></li>
                            </ul>
                        </div>
                        <div class="tab-content">
                            <div class="tab-pane fade" id="details">
                                <div class="col-md-12">
                                    <p> {{ product.description }}</p>
                                </div>
                            </div>

                            <div class="tab-pane fade" id="companyprofile">
                                <div class="col-sm-3">
                                    <div class="product-image-wrapper">
                                        <div class="single-products">
                                            <div class="productinfo text-center">
                                                <img src="{% static "images/home/gallery.jpg" %}" alt="">
                                                <h2>1.250.000 ريال</h2>
                                                <p>توضیحات کوتاه محصول</p>
                                                <button type="button" class="btn btn-default add-to-cart"><i
                                                        class="fa fa-shopping-cart"></i>افزودن به سبـد خریـد
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </div>

                            <div class="tab-pane fade" id="tag">
                                <div class="col-sm-3">
                                    <div class="product-image-wrapper">
                                        <div class="single-products">
                                            <div class="productinfo text-center">
                                                <img src="{% static "images/home/gallery.jpg" %}" alt="">
                                                <h2>1.250.000 ريال</h2>
                                                <p>توضیحات کوتاه محصول</p>
                                                <button type="button" class="btn btn-default add-to-cart"><i
                                                        class="fa fa-shopping-cart"></i>افزودن به سبـد خریـد
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </div>

                            <div class="tab-pane fade active in" id="reviews">
                                <div class="col-sm-12">


                                    <form id="main-post-form" class="post-form row" name="post-form"
                                          method="post"
                                          action="">
                                        <div class="form-group col-md-6">
                                            {% csrf_token %}
                                            {{ post_form.full_name }}
                                            {% for error in post_form.full_name.errors %}
                                                <p style="color: red;"> {{ error }}   </p>
                                            {% endfor %}

                                        </div>

                                        <div class="form-group col-md-6">

                                            {{ post_form.email }}
                                            {% for error in post_form.email.errors %}
                                                <p style="color: red;"> {{ error }}   </p>
                                            {% endfor %}

                                        </div>


                                        <div class="form-group col-md-12">

                                            {{ post_form.text }}
                                            {% for error in post_form.text.errors %}
                                                <p style="color: red;"> {{ error }}   </p>
                                            {% endfor %}

                                        </div>
                                        <div class="form-group col-md-12">
                                            <input type="submit" name="submit" class="btn btn-primary pull-right"
                                                   value="ارسـال">
                                        </div>


                                        <p><b>نظـر خود را بنویسیـد</b></p>
                                        <ul>
                                            {% if not product.comments.all %}
                                                <h1>No comments yet...</h1>

                                            {% else %}
                                                {% for comment in product.comments.all %}

                                                    <br/><br/>
                                                    <li class="col-sm-12">
                                                        {{ comment.name }} - {{ comment.date }}
                                                    </li>



                                                    {{ comment.body }}
                                                {% endfor %}
                                            {% endif %}

                                        </ul>

                                    </form>
                                </div>
                            </div>

                        </div>
                    </div><!--/category-tab-->

                    <div class="recommended_items"><!--recommended_items-->
                        <h2 class="title text-center">محصولات پیشنهادی</h2>

                        <div id="recommended-item-carousel" class="carousel slide" data-ride="carousel">
                            <div class="carousel-inner">
                                {% for product_list in related_products %}
                                    <div class="item {% if forloop.first %} active {% endif %}">
                                        {% for product in product_list %}
                                            {% include "products/product_item_components.html " with product=product %}

                                        {% endfor %}

                                    </div>
                                {% endfor %}


                            </div>
                            <a class="left recommended-item-control" href="#recommended-item-carousel"
                               data-slide="prev">
                                <i class="fa fa-angle-left"></i>
                            </a>
                            <a class="right recommended-item-control" href="#recommended-item-carousel"
                               data-slide="next">
                                <i class="fa fa-angle-right"></i>
                            </a>
                        </div>
                    </div><!--/recommended_items-->

                </div>

                <div class="col-sm-3">
                    <div class="left-sidebar">

                        {% render_partial "products_category_partial" %}

                    </div>
                </div>

            </div>
        </div>
    </section>
{% endblock %}

shop_products/templates/products/product_item_components.html
<div class="col-sm-4 pull-right">
    <div class="product-image-wrapper">
        <div class="single-products">
            <div class="productinfo text-center">
                <img src="{{ product.image.url }}" style="width: 250px; height: 250px;"
                     alt="">
                <h2>{{ product.price }}</h2>
                <p>{{ product.title }}</p>

            </div>


        </div>
        <div class="choose">
            <ul class="nav nav-pills nav-justified">
                <li><a href="{{ product.get_absolute_url }}"><i class="fa fa-plus-square"></i>مشاهده</a></li>

            </ul>
        </div>
    </div>
</div>

shop_products/templates/products/products_categories_partial.html
<h2>دسته بندی محصولات</h2>
<div class="panel-group category-products" id="accordian"><!--category-productsr-->
     <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><a href="/products">همه</a></h3>
            </div>
        </div>
    {% for category in categories %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title"><a href="/products/{{ category.name }}">{{ category.title }}</a></h4>
            </div>
        </div>
    {% endfor %}


</div><!--/category-productsr-->

shop_products/templates/products/products_list.html
{% extends "shared/_MainLayout.html" %}
{% load static %}
{% load render_partial %}
{% block content %}



    <section>
        <div class="container">
            <div class="row">

                <div class="col-sm-9 padding-right">
                    <div class="features_items"><!--features_items-->
                        <h2 class="title text-center">محصولات</h2>
                        {% for product in page_obj %}
                            {% include "products/product_item_components.html" with product=product %}
                        {% endfor %}



                        <div class="clearfix"></div>
                        <ul class="pagination">
                            {% if page_obj.has_previous %}
                                <li><a href="?page={{ page_obj.previous_page_number }}">قبلی</a></li>

                            {% endif %}
                            {% for page in paginator.page_range %}
                                {% if page == page_obj.number %}
                                    <li class="active"><a href="?page={{ page }}">{{ page }}</a></li>
                                {% else %}
                                    <li><a href="?page={{ page }}">{{ page }}</a></li>
                                {% endif %}
                            {% endfor %}
                            {% if page_obj.has_next %}
                                <li><a href="?page={{ page_obj.next_page_number }}">بعدی</a></li>

                            {% endif %}
                        </ul>
                    </div><!--features_items-->
                </div>

                <div class="col-sm-3">
                    <div class="left-sidebar">
                        {% render_partial "products_category_partial" %}

                    </div>
                </div>

            </div>
        </div>
    </section>
{% endblock %}